In [1]:
import pandas as pd 
import numpy as np 
import sklearn as sk 
from scipy.stats import kurtosis, skew

In [2]:
df_failure = pd.read_csv('PdM_failures.csv')
df_errors = pd.read_csv('PdM_errors.csv')
df_machines = pd.read_csv('PdM_machines.csv')
df_maint = pd.read_csv('PdM_maint.csv')
df_telemetry = pd.read_csv('PdM_telemetry.csv')
df = df_telemetry.copy()
df['datetime'] = pd.to_datetime(df['datetime'])
df['date'] = df['datetime'].dt.date
df['hour'] = df['datetime'].dt.strftime('%H:%M:%S')

In [16]:
#grouped_data = df.groupby(['date', 'machineID'])
#df_agg = pd.read_csv('aggregated.csv')

Unnamed: 0                         0
date                               0
machineID                          0
rotate_min                         0
rotate_max                         0
rotate_<lambda_0>                  0
rotate_<lambda_1>                  0
rotate_<lambda_2>                  0
rotate_median                      0
rotate_mean                        0
volt_min                           0
volt_max                           0
volt_<lambda_0>                    0
volt_<lambda_1>                    0
volt_<lambda_2>                    0
volt_median                        0
volt_mean                          0
pressure_min                       0
pressure_max                       0
pressure_<lambda_0>                0
pressure_<lambda_1>                0
pressure_<lambda_2>                0
pressure_median                    0
pressure_mean                      0
vibration_min                      0
vibration_max                      0
vibration_<lambda_0>               0
vibration_<lambda_1>               0
vibration_<lambda_2>               0
vibration_median                   0
vibration_mean                     0
rotate_mape_                       0
rotate_rmse_                       0
rotate_energy_                     0
volt_mape_                         0
volt_rmse_                         0
volt_energy_                       0
pressure_mape_                     0
pressure_rmse_                     0
pressure_energy_                   0
vibration_mape_                    0
vibration_rmse_                    0
vibration_energy_                  0
fft_rotate_magnitude_mape_         0
fft_rotate_magnitude_rmse_         0
fft_rotate_magnitude_energy_       0
fft_pressure_magnitude_mape_       0
fft_pressure_magnitude_rmse_       0
fft_pressure_magnitude_energy_     0
fft_vibration_magnitude_mape_      0
fft_vibration_magnitude_rmse_      0
fft_vibration_magnitude_energy_    0
fft_volt_magnitude_mape_           0
fft_volt_magnitude_rmse_           0
fft_volt_magnitude_energy_         0
dtype: int64

In [13]:
# Function to calculate Mean Absolute Percentage Error (MAPE)
def mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# Function to calculate Root Mean Squared Error (RMSE)
def rmse(y_true, y_pred):
    return np.sqrt(np.mean((y_true - y_pred)**2))

# Function to calculate cross-correlation between two signals
def cross_correlation(x, y):
    return np.correlate(x, y, mode='same')

# Function to calculate energy of the signal
def energy(x):
    return np.sum(x**2)/100


df['fft_rotate'] = np.fft.fft(df['rotate'])
df['fft_rotate_magnitude'] = np.abs(df['fft_rotate'])
df['fft_rotate_phase'] = np.angle(df['fft_rotate'])
df['fft_vibration'] = np.fft.fft(df['vibration'])
df['fft_vibration_magnitude'] = np.abs(df['fft_vibration'])
df['fft_vibration_phase'] = np.angle(df['fft_vibration'])
df['fft_pressure'] = np.fft.fft(df['pressure'])
df['fft_pressure_magnitude'] = np.abs(df['fft_pressure'])
df['fft_pressure_phase'] = np.angle(df['fft_pressure'])
df['fft_volt'] = np.fft.fft(df['volt'])
df['fft_volt_magnitude'] = np.abs(df['fft_volt'])
df['fft_volt_phase'] = np.angle(df['fft_volt'])

In [18]:
# Step 1: Group the DataFrame by 'date' and 'machineID'
grouped_data = df.groupby(['date', 'machineID'])

# Step 2: Apply aggregation functions on sensor columns for each group
aggregated_data = grouped_data.agg({
    'rotate': ['min', 'max', lambda x: kurtosis(x), lambda x: skew(x), lambda x: x.quantile(0.75) - x.quantile(0.25), 'median', 'mean','count'],
    'volt': ['min', 'max', lambda x: kurtosis(x), lambda x: skew(x), lambda x: x.quantile(0.75) - x.quantile(0.25), 'median', 'mean','count'],
    'pressure': ['min', 'max', lambda x: kurtosis(x), lambda x: skew(x), lambda x: x.quantile(0.75) - x.quantile(0.25), 'median', 'mean','count'],
    'vibration': ['min', 'max', lambda x: kurtosis(x), lambda x: skew(x), lambda x: x.quantile(0.75) - x.quantile(0.25), 'median', 'mean','count'],
    'fft_rotate_magnitude': ['min', 'max',lambda x: skew(x), lambda x: x.quantile(0.75) - x.quantile(0.25), 'median', 'mean','count'],
    'fft_pressure_magnitude': ['min', 'max',lambda x: skew(x), lambda x: x.quantile(0.75) - x.quantile(0.25), 'median', 'mean','count'],
    'fft_vibration_magnitude': ['min', 'max',lambda x: skew(x), lambda x: x.quantile(0.75) - x.quantile(0.25), 'median', 'mean','count'],
    'fft_volt_magnitude': ['min', 'max',lambda x: skew(x), lambda x: x.quantile(0.75) - x.quantile(0.25), 'median', 'mean','count']
})

# Add point MAPE, RMSE, cross-correlation, energy, and frequency domain features
for sensor in ['rotate','volt','pressure','vibration']:
    aggregated_data[sensor + '_mape'] = grouped_data[sensor].apply(lambda x: mape(x, x.median()))
    aggregated_data[sensor + '_rmse'] = grouped_data[sensor].apply(lambda x: rmse(x, x.median()))
    aggregated_data[sensor + '_energy'] = grouped_data[sensor].apply(lambda x: energy(x))

# Step 3: Flatten the multi-level column index
aggregated_data.columns = ['_'.join(col).strip() for col in aggregated_data.columns.values]

# Optionally, you can reset the index to get 'date' and 'machineID' as separate columns
aggregated_data.reset_index(inplace=True)

aggregated_data

,date,machineID,rotate_min,rotate_max,rotate_<lambda_0>,rotate_<lambda_1>,rotate_<lambda_2>,rotate_median,rotate_mean,rotate_count,...,rotate_energy_,volt_mape_,volt_rmse_,volt_energy_,pressure_mape_,pressure_rmse_,pressure_energy_,vibration_mape_,vibration_rmse_,vibration_energy_
0,2015-01-01,1,346.149335,527.349825,-0.790617,0.156417,78.750562,432.850118,440.515328,18,...,3.534774e+06,4.575802,9.302293,506944.536253,8.604186,10.548155,176625.744178,11.743593,5.704275,29431.491969
1,2015-01-01,2,369.738792,543.802540,0.093926,0.364777,47.779860,444.667492,445.200094,18,...,3.597414e+06,5.363811,12.454714,545808.704982,8.239716,10.058523,184452.325123,8.772652,4.556427,31277.993415
2,2015-01-01,3,382.648588,531.139800,-1.240765,0.072763,70.039863,461.496434,454.152365,18,...,3.753234e+06,4.774495,10.525317,515618.561604,8.394769,10.250305,183194.991205,11.791365,5.089333,24161.025527
3,2015-01-01,4,327.243866,551.327283,0.721164,0.150727,43.058493,444.503545,447.758764,18,...,3.654330e+06,7.806184,16.013438,515053.771373,5.826959,7.953796,174459.158479,9.420820,4.935726,31549.278555
4,2015-01-01,5,308.578855,539.732729,-0.368387,-0.589313,94.737470,461.502012,450.183235,18,...,3.714905e+06,6.147190,14.366183,543074.162357,10.299086,12.004830,173850.777980,7.941181,4.015031,28072.688179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36595,2016-01-01,96,360.998546,520.313613,-1.145422,-0.703820,78.128461,487.628145,458.058551,7,...,1.492282e+06,10.335148,19.816359,190310.198977,6.149300,7.904610,68734.970108,8.110237,3.908547,10203.307989
36596,2016-01-01,97,392.702026,522.348411,-1.148606,0.216379,63.044880,458.143799,449.519362,7,...,1.427817e+06,7.620247,15.388704,216625.508389,7.379155,9.183053,70863.379639,9.740416,5.066905,11797.848702
36597,2016-01-01,98,389.828191,526.828641,-0.930038,-0.102140,53.929362,450.198921,461.853080,7,...,1.505954e+06,7.503993,18.609660,214160.952758,5.883867,8.264347,102175.565648,9.183485,5.863154,12712.826688
36598,2016-01-01,99,416.284422,491.390537,-1.500171,0.009017,44.860950,462.373730,450.518923,7,...,1.425951e+06,6.280918,13.993774,201768.185837,3.266363,4.356264,69548.043410,9.846259,5.106796,12653.144852
36599,2016-01-01,100,395.222827,496.096870,-1.016045,0.048475,37.907325,446.207972,445.693412,7,...,1.397913e+06,5.071955,11.723013,216899.228536,6.347523,9.121205,67014.881856,10.174918,5.301781,13794.258348

In [20]:
#aggregated_data.to_csv('aggregated.csv')
df_agg = aggregated_data.copy()

In [21]:
def merger_with_duplicate_row_remover(df1 , df2 ):
    print("*"*200)
    if ("date" in df2.columns):
        merged_df =pd.merge(df1, df2, on=['date','machineID'],how='left')
        merged_df = merged_df.replace(np.NaN,0)
        print("Shape of left dataset:                             ",df1.shape)
        print("Shape of the right dataset:                        ",df2.shape)
        print("Shape of merged dataset before checking duplicates:",merged_df.shape)

        #creating an extra column that will have unique datetime+machineID
        merged_df['combo'] = merged_df['machineID'].astype(str) +"~"+ merged_df['date'].astype(str) 
        # merged_df['combo'].value_counts() to check duplicates Anything greater than 1 will be duplicated
        li = merged_df['combo'].value_counts()
        valids = li[li > 1].index  
        print("Duplicate rows found:", len(valids))

        merged_df[merged_df['combo'].isin(valids)] #create a dataframe To get rows of deficit indices
        # Here dropping the duplicate rows becomes essential 
        merged_df = merged_df.drop_duplicates(subset=['combo']) 
        print("Duplicates rows removed:", len(valids)/2 )
        print("Shape of merged dataset after removing duplicate columns:", merged_df.shape)
    else:
        # Machine dataframe has no datatime plus no duplicates
        merged_df =pd.merge(df1, df2, on=['machineID'],how='left')
        merged_df = merged_df.replace(np.NaN,0)
        print("Shape of left dataset:                             ",df1.shape)
        print("Shape of the right dataset:                        ",df2.shape)
        print("Shape of merged dataset before checking duplicates:",merged_df.shape)
        
    return merged_df

err = df_errors.copy()
err['datetime'] = pd.to_datetime(err['datetime'])
err['date'] = err['datetime'].dt.date
maint = df_maint.copy()
maint['datetime'] = pd.to_datetime(maint['datetime'])
maint['date'] = maint['datetime'].dt.date

fail = df_failure.copy()
fail['datetime'] = pd.to_datetime(fail['datetime'])
fail['date'] = fail['datetime'].dt.date

data = pd.merge(df_agg, df_machines, how= 'left', on='machineID')
data = merger_with_duplicate_row_remover(data,err)
data = merger_with_duplicate_row_remover(data,maint)
data = merger_with_duplicate_row_remover(data,fail)
data.head()

********************************************************************************************************************************************************************************************************
Shape of left dataset:                              (36600, 76)
Shape of the right dataset:                         (3919, 4)
Shape of merged dataset before checking duplicates: (37078, 78)
Duplicate rows found: 422
Duplicates rows removed: 211.0
Shape of merged dataset after removing duplicate columns: (36600, 79)
********************************************************************************************************************************************************************************************************
Shape of left dataset:                              (36600, 79)
Shape of the right dataset:                         (3286, 4)
Shape of merged dataset before checking duplicates: (37323, 81)
Duplicate rows found: 723
Duplicates rows removed: 361.5
Shape of merged dataset after removing duplicate columns: (36600, 81)
********************************************************************************************************************************************************************************************************
Shape of left dataset:                              (36600, 81)
Shape of the right dataset:                         (761, 4)
Shape of merged dataset before checking duplicates: (36643, 83)
Duplicate rows found: 43
Duplicates rows removed: 21.5
Shape of merged dataset after removing duplicate columns: (36600, 83)

,date,machineID,rotate_min,rotate_max,rotate_<lambda_0>,rotate_<lambda_1>,rotate_<lambda_2>,rotate_median,rotate_mean,rotate_count,...,vibration_energy_,model,age,datetime_x,errorID,combo,datetime_y,comp,datetime,failure
0,2015-01-01,1,346.149335,527.349825,-0.790617,0.156417,78.750562,432.850118,440.515328,18,...,29431.491969,model3,18,0,0,1~2015-01-01,0,0,0,0
1,2015-01-01,2,369.738792,543.802540,0.093926,0.364777,47.779860,444.667492,445.200094,18,...,31277.993415,model4,7,0,0,2~2015-01-01,0,0,0,0
2,2015-01-01,3,382.648588,531.139800,-1.240765,0.072763,70.039863,461.496434,454.152365,18,...,24161.025527,model3,8,0,0,3~2015-01-01,0,0,0,0
3,2015-01-01,4,327.243866,551.327283,0.721164,0.150727,43.058493,444.503545,447.758764,18,...,31549.278555,model3,7,0,0,4~2015-01-01,0,0,0,0
4,2015-01-01,5,308.578855,539.732729,-0.368387,-0.589313,94.737470,461.502012,450.183235,18,...,28072.688179,model3,2,0,0,5~2015-01-01,0,0,0,0

In [23]:
#Further target column will be transformed with label encoding ,and other categorical columns with dummy encoding 

data_encoded = pd.get_dummies(data, columns=['comp', 'errorID', 'model'], drop_first=True)
data_encoded = data_encoded.replace({'failure' : 0}, '0')
print(data_encoded.failure.unique()) #To verify the change 
data_encoded.head(2)
data_encoded.drop(["combo","datetime_x", 'datetime_y','datetime'] , axis=1 , inplace=True)

['0' 'comp1' 'comp4' 'comp3' 'comp2']

In [29]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Get X_train and y_train : original training data
X_train, X_test, y_train, y_test = train_test_split(data_encoded.drop(['failure','date'], axis=1), data_encoded['failure'], test_size=0.2, random_state=42)

# Split the data into training set and validation set (80% training, 20% validation)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.18, random_state=42)

# Now we have X_train and y_train as the new training set, and X_val and y_val as the validation set.

# Fit the encoder on y_train to learn the mapping
enc = LabelEncoder()
enc.fit(y_train)
enc.fit(y_val)

y_train = enc.transform(y_train)
y_test = enc.transform(y_test)
y_val_encoded = enc.transform(y_val)

#Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_val = scaler.transform(X_val)

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
# Create and train the Logistic Regression model
mdl = LogisticRegression(max_iter=9000)
mdl.fit(X_train, y_train)

# Predict on the validation set
y_val_pred = mdl.predict(X_val) 
y_val_pred_prob = mdl.predict_proba(X_val)[:,1]    # Predicts the probability of the validation data

# Evaluate the model on the validation set
print("Validation Set Evaluation:")
print("Accuracy: ", accuracy_score(y_val_encoded, y_val_pred))
print("Precision: ", precision_score(y_val_encoded, y_val_pred, average='macro'))
print("Recall: ", recall_score(y_val_encoded, y_val_pred, average='macro'))
print("F1: ", f1_score(y_val_encoded, y_val_pred, average='macro'))
print("Confusion Matrix:")
print(confusion_matrix(y_val_encoded, y_val_pred))
print("Classification Report:")
print(classification_report(y_val_encoded, y_val_pred))

# Predict on the test set
y_test_pred = mdl.predict(X_test) 
y_test_pred_prob = mdl.predict_proba(X_test)[:,1]    # Predicts the probability of the test data

# Evaluate the model on the test set
print("Test Set Evaluation:")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("Precision: ", precision_score(y_test, y_test_pred, average='macro'))
print("Recall: ", recall_score(y_test, y_test_pred, average='macro'))
print("F1: ", f1_score(y_test, y_test_pred, average='macro'))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
print("Classification Report:")
print(classification_report(y_test, y_test_pred))

Validation Set Evaluation:
Accuracy:  0.9891861126920888
Precision:  0.7563061323640431
Recall:  0.6915562928633812
F1:  0.7158500604333937
Confusion Matrix:
[[5158    7    8    4    1]
 [  10    9    1    2    0]
 [  12    0   17    0    0]
 [   3    0    0   13    0]
 [   7    1    1    0   17]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      5178
           1       0.53      0.41      0.46        22
           2       0.63      0.59      0.61        29
           3       0.68      0.81      0.74        16
           4       0.94      0.65      0.77        26

    accuracy                           0.99      5271
   macro avg       0.76      0.69      0.72      5271
weighted avg       0.99      0.99      0.99      5271

Test Set Evaluation:
Accuracy:  0.9896174863387979
Precision:  0.7704259251947491
Recall:  0.7211182655847357
F1:  0.7408013958073031
Confusion Matrix:
[[7160    9   17    2    1]
 [  19   16    0    1    0]
 [  10    1   26    1    3]
 [   2    0    0   27    0]
 [   9    1    0    0   15]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      7189
           1       0.59      0.44      0.51        36
           2       0.60      0.63      0.62        41
           3       0.87      0.93      0.90        29
           4       0.79      0.60      0.68        25

    accuracy                           0.99      7320
   macro avg       0.77      0.72      0.74      7320
weighted avg       0.99      0.99      0.99      7320